apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  selector:
    app: logstash
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash-container
          image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2