apiVersion: v1
kind: Service
metadata:
  name: opensearch-service
spec:
  selector:
    app: opensearch
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch-container
          image: opensearchproject/opensearch:latest
          env:
            - name: cluster.name
              value: 'opensearch-cluster'
            - name: node.name
              value: 'opensearch-node1'
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: 'true'
            - name: DISABLE_SECURITY_PLUGIN
              value: 'true'
            - name: discovery.type
              value: 'single-node'
            - name: OPENSEARCH_JAVA_OPTS
              value: '-Xms512m -Xmx512m'


