functions:
  cold:
    handler: ./functions/coldFunctions/handler.cold
    name: ${self:service}-${self:provider.stage}-cold
    events:
      - http:
          path: cold
          method: get
#          integration: lambda
#          request:
#            template:
#              application/json: '{ "stageVariables" : { "SERVERLESS_YML_VARIABLE" : "${self:provider.stage}" } }'
    warmup:
      officeWarmer:
        enabled: false
      outOfOfficeWarmer:
        enabled: false

  warm:
    handler: ./functions/warmFunctions/handler.warm
    name: ${self:service}-${self:provider.stage}-warm
    events:
      - http:
          path: warm
          method: get
    warmup:
      officeWarmer:
        enabled: false
      outOfOfficeWarmer:
        enabled: false

  warm2:
    handler: ./functions/warmFunctions/handler2.warm2
    name: ${self:service}-${self:provider.stage}-warm2
    events:
      - http:
          path: warm2
          method: get
    warmup:
      officeWarmer:
        enabled: false
      outOfOfficeWarmer:
        enabled: false
#  warmUpHandler:
#    handler: ./functions/warmer/handler.warmer
#    name: ${self:service}-${self:provider.stage}-warmer
#    events:
#      - schedule: rate(1 minute)

#          integration: lambda
#          request:
#            template:
#              application/json: '{ "stageVariables" : { "SERVERLESS_ALIAS" : "${self:provider.stage}" } }'
