functions:
  cold:
    handler: entry/slsWarmer.coldHandler
    name: ${self:service}-${self:provider.stage}-cold
    events:
      - http:
          path: cold
          method: get
    warmup:
      officeWarmer:
        enabled: false
      outOfOfficeWarmer:
        enabled: false

  warm:
    handler: entry/slsWarmer.warmHandler
    name: ${self:service}-${self:provider.stage}-warm
    events:
      - http:
          path: warm
          method: get
    warmup:
      officeWarmer:
        enabled: false
      outOfOfficeWarmer:
        enabled: false

#  warmUpHandler:
#    handler: ./functions/warmer/handler.warmer
#    name: ${self:service}-${self:provider.stage}-warmer
#    events:
#      - schedule: rate(1 minute)